### ISSUE TITLE
HtResponse.java:39-42: We need decorators for HtResponse...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#64]
The puzzle `62-02593012` from #62 has to be resolved:

https://github.com/yegor256/cactoos-http/blob/795e57c6d3c16283c56b66c62a765f5605aadd7d/src/main/java/org/cactoos/http/HtResponse.java#L39-L42

The puzzle was created by George Aristy on 28-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#64](https://github.com/yegor256/cactoos-http/issues/64) is now in scope, role is `DEV`

**Comment by llorllale** [comment]
@0pdd let me amend the requirement in this puzzle: none of the example decorators should close the inputstream. We could have an `HtAutoClosedResponse` though. Consider that in #63 we basically want to keep the socket alive unless we explicitly close it.

Example:

```java
new HtAutoClosedResponse(            //automatically closes stream/socket when EOF is reached  
    new HtContentLengthResponse(     //reads inputstream up to length received in Content-Length
        new HtResponse(              //inputstream as-is
            new HtWire("host"),
            "request"
        )
    )
)
```

**Comment by 0pdd** [comment]
> @0pdd let me amend the requirement in this puzzle: none of the example decorators should close the i...

I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by 0crat** [comment]
The job [#64](https://github.com/yegor256/cactoos-http/issues/64) assigned to @tomascury[/z](https://www.0crat.com/u/tomascury), here is [why](https://www.0crat.com/footprint/C63314D6Z/165b9ea8-b678-4502-8b54-17a4bb1f8130); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @tomascury[/z](https://www.0crat.com/u/tomascury) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos-http/issues/64#issuecomment-466769141))

@llorllale The user @tomascury[/z](https://www.0crat.com/u/tomascury) resigned from [#64](https://github.com/yegor256/cactoos-http/issues/64), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#64](https://github.com/yegor256/cactoos-http/issues/64) assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/4d229dbd-ae78-4bc5-b66b-5d7cf28ba1d2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#64](https://github.com/yegor256/cactoos-http/issues/64) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/c4bbe7fe-03e1-4cb7-942d-502bca1f4ea6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@llorllale I'm not sure what is expected of DEV here, implement `HtAutoClosedResponse`?

**Comment by llorllale** [comment]
@victornoel you can start with that and leave a puzzle for the others (eg. `HtContentLengthResponse`)

**Comment by victornoel** [comment]
@0crat wait I'm on it

**Comment by 0crat** [comment]
> @0crat wait I'm on it ([here](https://github.com/yegor256/cactoos-http/issues/64#issuecomment-478756136))

@victornoel The impediment for [#64](https://github.com/yegor256/cactoos-http/issues/64) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@llorllale I've implemented it in #79

**Comment by 0pdd** [comment]
The puzzle `62-02593012` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#80](https://github.com/yegor256/cactoos-http/issues/80), [#81](https://github.com/yegor256/cactoos-http/issues/81) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
The job [#64](https://github.com/yegor256/cactoos-http/issues/64) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#81](https://github.com/yegor256/cactoos-http/issues/81) is still not solved; solved: [#80](https://github.com/yegor256/cactoos-http/issues/80).
